services:
    mpp-server-dev2:
        build: .
        tty: true
        stdin_open: true
        restart: always
        user: root
        ports:
            - "8443:8443"
        volumes:
            - ./config:/usr/src/app/config
            - ./public:/usr/src/app/public
            - ./prisma:/usr/src/app/prisma
            - ./logs:/usr/src/app/logs
