topButtons: git-links
disableChat: false
winter: false
enableSlide: false
createdRoomSocialLinks: false
playingAloneSocialLinks: false
motd: This site makes a lot of sound! You may want to adjust the volume before
    continuing.
hideChatOnDisconnect: false
