owner:
    - clearChat
    - vanish
    - chsetAnywhere
    - chownAnywhere
    - usersetOthers
    - siteBan
    - siteBanAnyReason
    - siteBanAnyDuration

admin:
    - clearChat
    - vanish
    - chsetAnywhere
    - chownAnywhere
    - usersetOthers
    - siteBan
    - siteBanAnyReason
    - siteBanAnyDuration

mod:
    - clearChat
    - vanish
    - chsetAnywhere
    - chownAnywhere
    - usersetOthers
    - siteBan
    - siteBanAnyReason

trialmod:
    - clearChat
    - vanish
    - chsetAnywhere
    - chownAnywhere
    - siteBan
