user:
    normal:
        a: 250
        m: 40
        ch: 100
        kickban: 50
        unban: 50
        t: 10
        +ls: 15
        -ls: 15
        chown: 500
        +custom: 10
        -custom: 10
        hi: 100
        bye: 100
        devices: 100
        admin message: 10
    chains:
        userset:
            interval: 60000
            num: 1000
        chset:
            interval: 60000
            num: 1024
        n:
            interval: 1000
            num: 2000
        custom:
            interval: 1000
            num: 1024
crown:
    normal:
        a: 50
        m: 40
        ch: 100
        kickban: 50
        unban: 50
        t: 10
        +ls: 15
        -ls: 15
        chown: 500
        +custom: 10
        -custom: 10
        hi: 100
        bye: 100
        devices: 100
        admin message: 10
    chains:
        userset:
            interval: 60000
            num: 1000
        chset:
            interval: 60000
            num: 1024
        n:
            interval: 1000
            num: 2000
        custom:
            interval: 1000
            num: 1024
admin:
    normal:
        a: 10
        m: 10
        ch: 10
        kickban: 10
        unban: 10
        t: 10
        +ls: 10
        -ls: 10
        chown: 10
        +custom: 10
        -custom: 10
        hi: 10
        bye: 10
        devices: 10
        admin message: 10
    chains:
        userset:
            interval: 500
            num: 100000
        chset:
            interval: 60000
            num: 1024
        n:
            interval: 50
            num: 2400000
        custom:
            interval: 60000
            num: 2000000
